export const dancingPills = [
  { image: "https://roar-ai.b-cdn.net/dancing_pills/2bvH7SaVsmLOzAlkff.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/2RyiAwHFMaozeUToD0.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/3sa9Jx4hDBo5UPX6VR.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/4k4qF5hi8zlzJJq7qi.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/4RjVINGRe7LM4ZjvGh.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/9doNIK5BZYcUWzXL1R.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/fOtfxu3rdXalzkWcqK.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/GTTm7XxWuRaqtM0Mm0.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/h5HHp2Nb0g9dp5J4lV.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/itdyx8kKVkerxn0uUe.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/Ku2wo0uG5a1v2cEvKU.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/LYHbw1LcSIDsPiCRrv.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/S1EY3oF4bO3epu8x33.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/UO42Ljd1cPdmHSOaXE.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/uqPd0oTw5a3L9nqMdd.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/V8csp4bycSkJ1exqTK.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/wATml87Z0EEl1lfjMS.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/wZALv9jVAastsGgqes.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/yoiVMo6QwBAvUspSt4.jpg" },
  { image: "https://roar-ai.b-cdn.net/dancing_pills/LYHbw1LcSIDsPiCRrv.jpg" },
];