export const dancingPills = [
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/2bvH7SaVsmLOzAlkff.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/2RyiAwHFMaozeUToD0.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/3sa9Jx4hDBo5UPX6VR.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/4k4qF5hi8zlzJJq7qi.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/4RjVINGRe7LM4ZjvGh.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/9doNIK5BZYcUWzXL1R.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/fOtfxu3rdXalzkWcqK.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/GTTm7XxWuRaqtM0Mm0.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/h5HHp2Nb0g9dp5J4lV.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/itdyx8kKVkerxn0uUe.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/Ku2wo0uG5a1v2cEvKU.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/LYHbw1LcSIDsPiCRrv.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/S1EY3oF4bO3epu8x33.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/UO42Ljd1cPdmHSOaXE.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/uqPd0oTw5a3L9nqMdd.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/V8csp4bycSkJ1exqTK.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/wATml87Z0EEl1lfjMS.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/wZALv9jVAastsGgqes.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/yoiVMo6QwBAvUspSt4.gif" },
  { image: "https://roar-ai.b-cdn.net/gifs/dancing_pills/LYHbw1LcSIDsPiCRrv.gif" },
];
