import { LanguageOption } from "@/types/types";

export const languages: LanguageOption[] = [
  { label: "Arabic", lang_code: "Language.AR", gemini_code: "ar-XA" },
  { label: "Bengali (India)", lang_code: "Language.BN_IN", gemini_code: "bn-IN" },
  { label: "Chinese (Mandarin)", lang_code: "Language.CMN_CN", gemini_code: "cmn-CN" },
  { label: "German (Germany)", lang_code: "Language.DE_DE", gemini_code: "de-DE" },
  { label: "English (US)", lang_code: "Language.EN_US", gemini_code: "en-US" },
  { label: "English (Australia)", lang_code: "Language.EN_AU", gemini_code: "en-AU" },
  { label: "English (UK)", lang_code: "Language.EN_GB", gemini_code: "en-GB" },
  { label: "English (India)", lang_code: "Language.EN_IN", gemini_code: "en-IN" },
  { label: "Spanish (Spain)", lang_code: "Language.ES_ES", gemini_code: "es-ES" },
  { label: "Spanish (US)", lang_code: "Language.ES_US", gemini_code: "es-US" },
  { label: "French (France)", lang_code: "Language.FR_FR", gemini_code: "fr-FR" },
  { label: "French (Canada)", lang_code: "Language.FR_CA", gemini_code: "fr-CA" },
  { label: "Gujarati (India)", lang_code: "Language.GU_IN", gemini_code: "gu-IN" },
  { label: "Hindi (India)", lang_code: "Language.HI_IN", gemini_code: "hi-IN" },
  { label: "Indonesian", lang_code: "Language.ID_ID", gemini_code: "id-ID" },
  { label: "Italian (Italy)", lang_code: "Language.IT_IT", gemini_code: "it-IT" },
  { label: "Japanese (Japan)", lang_code: "Language.JA_JP", gemini_code: "ja-JP" },
  { label: "Kannada (India)", lang_code: "Language.KN_IN", gemini_code: "kn-IN" },
  { label: "Korean (Korea)", lang_code: "Language.KO_KR", gemini_code: "ko-KR" },
  { label: "Malayalam (India)", lang_code: "Language.ML_IN", gemini_code: "ml-IN" },
  { label: "Marathi (India)", lang_code: "Language.MR_IN", gemini_code: "mr-IN" },
  { label: "Dutch (Netherlands)", lang_code: "Language.NL_NL", gemini_code: "nl-NL" },
  { label: "Polish (Poland)", lang_code: "Language.PL_PL", gemini_code: "pl-PL" },
  { label: "Portuguese (Brazil)", lang_code: "Language.PT_BR", gemini_code: "pt-BR" },
  { label: "Russian (Russia)", lang_code: "Language.RU_RU", gemini_code: "ru-RU" },
  { label: "Tamil (India)", lang_code: "Language.TA_IN", gemini_code: "ta-IN" },
  { label: "Telugu (India)", lang_code: "Language.TE_IN", gemini_code: "te-IN" },
  { label: "Thai (Thailand)", lang_code: "Language.TH_TH", gemini_code: "th-TH" },
  { label: "Turkish (Turkey)", lang_code: "Language.TR_TR", gemini_code: "tr-TR" },
  { label: "Vietnamese (Vietnam)", lang_code: "Language.VI_VN", gemini_code: "vi-VN" },
];